"""Canvi model usuari

Revision ID: 5a79009373d3
Revises: 61d3d4cc717d
Create Date: 2025-03-03 23:45:03.615023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a79009373d3'
down_revision: Union[str, None] = '61d3d4cc717d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuaris', sa.Column('superusuari', sa.Boolean(), nullable=True))
    op.add_column('usuaris', sa.Column('adreça', sa.String(length=255), nullable=False))
    op.add_column('usuaris', sa.Column('instagram', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('foto1', sa.LargeBinary(), nullable=True))
    op.add_column('usuaris', sa.Column('foto2', sa.LargeBinary(), nullable=True))
    op.add_column('usuaris', sa.Column('foto3', sa.LargeBinary(), nullable=True))
    op.add_column('usuaris', sa.Column('foto4', sa.LargeBinary(), nullable=True))
    op.add_column('usuaris', sa.Column('foto5', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuaris', 'foto5')
    op.drop_column('usuaris', 'foto4')
    op.drop_column('usuaris', 'foto3')
    op.drop_column('usuaris', 'foto2')
    op.drop_column('usuaris', 'foto1')
    op.drop_column('usuaris', 'instagram')
    op.drop_column('usuaris', 'adreça')
    op.drop_column('usuaris', 'superusuari')
    # ### end Alembic commands ###
