"""Canvis

Revision ID: 61d3d4cc717d
Revises: a3093ce29f24
Create Date: 2025-03-02 23:41:39.672803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61d3d4cc717d'
down_revision: Union[str, None] = 'a3093ce29f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('festes', sa.Column('adreca', sa.String(length=255), nullable=False))
    op.add_column('festes', sa.Column('ciutat', sa.String(length=255), nullable=False))
    op.alter_column('usuaris', 'nom',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuaris', 'nom',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('festes', 'ciutat')
    op.drop_column('festes', 'adreca')
    # ### end Alembic commands ###
