"""Test

Revision ID: a3093ce29f24
Revises: d1f469f66216
Create Date: 2025-03-02 18:17:51.956524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3093ce29f24'
down_revision: Union[str, None] = 'd1f469f66216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuaris',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('contrasenya_hash', sa.String(length=255), nullable=False),
    sa.Column('es_organitzador', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('festes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('hora_inici', sa.Time(), nullable=False),
    sa.Column('hora_final', sa.Time(), nullable=False),
    sa.Column('punt_lila', sa.Boolean(), nullable=True),
    sa.Column('targeta', sa.Boolean(), nullable=True),
    sa.Column('cartell_imatge', sa.LargeBinary(), nullable=True),
    sa.Column('organitzador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organitzador_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguidors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('organitzador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organitzador_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuari_id', 'organitzador_id', name='uq_usuari_organitzador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidors')
    op.drop_table('festes')
    op.drop_table('usuaris')
    # ### end Alembic commands ###
